### ISSUE TITLE
Get Iplayer Automator not downloading ITV programmes on Mac OS Ventura in the UK.

### ISSUE THREAD

**Issue by Swilly6vic** [Ascoware/get-iplayer-automator#434] opened 2022-12-27 16:22 UTC
I selected the ITV programmes I wanted to download but Get Iplayer Automator lists the programmes in the download queue but them after clicking on start the ITV programmes show downloaded and then moves on the next programme. A folder is created in the download folder but there is 0 content in the folder. I have selected Doc Martin: series 10, but the same thing happens with other ITV programmes.
---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*
<img width="799" alt="Screenshot 2022-12-27 at 16 18 26" src="https://user-images.githubusercontent.com/28845258/209693456-180496cc-7daa-45df-97f1-7ad07e71896f.png">
<img width="817" alt="Screenshot 2022-12-27 at 16 21 17" src="https://user-images.githubusercontent.com/28845258/209693483-c74da7bb-bb6b-4a5f-ba55-9ead14801ccd.png">
<img width="1050" alt="Screenshot 2022-12-27 at 16 21 29" src="https://user-images.githubusercontent.com/28845258/209693503-65e86e9c-69be-438f-a08d-4872168c4278.png">

**Comment by skovatch** [comment] 2022-12-27 18:16
What version of GIA is this? ITV downloads have been broken since early December, and you shouldn't be able to cache them either.

**Comment by Swilly6vic** [comment] 2022-12-28 09:32
It’s the latest version of GIAStephen Williams Sent from my iPhoneOn 27 Dec 2022, at 18:16, Scott Kovatch ***@***.***> wrote:﻿
What version of GIA is this? ITV downloads have been broken since early December, and you shouldn't be able to cache them either.

**Comment by PhgSpa** [comment] 2022-12-28 21:03
I have just downloaded 1.24.4 to my 14" MacBook Pro, running Ventura. When I try to run it I get the message

"Get iPlayer Automator.app" can't be opened because Apple cannot check it for malicious software.

How do I get it to run?

**Comment by skovatch** [comment] 2022-12-29 09:48
> I have just downloaded 1.24.4 to my 14" MacBook Pro, running Ventura. When I try to run it I get the message
> 
> "Get iPlayer Automator.app" can't be opened because Apple cannot check it for malicious software.
> 
> How do I get it to run?

Control-click on the application icon, then choose 'Open'. Your "Privacy & Security" settings are only allowing applications from the App Store, but this will make an exception for GiA.

(Also, please open a new issue for things like this.)

**Comment by skovatch** [comment] 2022-12-29 09:51
OK, I see the problem -- no new ITV shows are being cached, but the search function is still including ITV results, so anything you cached in the past is still being found.

**Comment by Swilly6vic** [comment] 2022-12-29 14:07
Ok that makes sense. Do you know when a fix for GIA for ITV programmes is likely to be completed? Stephen Williams Sent from my iPhoneOn 29 Dec 2022, at 09:51, Scott Kovatch ***@***.***> wrote:﻿
OK, I see the problem -- no new ITV shows are being cached, but the search function is still including ITV results, so anything you cached in the past is still being found.

**Comment by skovatch** [comment] 2022-12-29 18:59
Follow #428 for more details on ITV downloads.

**Comment by skovatch** [comment] 2023-01-16 04:34
Duplicate of #428.

**Closed by skovatch** 2023-01-16 04:34 UTC
