### ISSUE TITLE
Would like preference to not include "Season" in file name or directory name

### ISSUE THREAD

**Issue by adbeckett** [Ascoware/get-iplayer-automator#318] opened 2021-03-23 20:47 UTC
Using version 1.21.5

Recently, a feature was added to make ITV programmes show the Season/Series number as part of the name. This is very helpful when searching in get-iplayer-automator as it makes it much easier to find the right series when looking at a long-running programme with many series that is repeated frequently.

However, it also means that the saved results get put in a directory (folder) with "Season 4" (for example) included in the name, and the file name is also something like:

Unforgotten - Season 4.s04e05.Episode 5.mp4

The problem I have with this is that Plex gets confused by the Season number part and so fails to match the program unless I manually tell it to search for just "Unforgotten". If the file/folder name is changed to just Unforgotten.s04e05.Episode 5.mp4 then it matches with no problem (the "Episode 5" bit could be removed too).

This has been an issue with BBC programmes for some time, but is now happening for ITV programmes with the latest changes.

So, this is a request for a preference to allow the Season/Series name to show up in the search/download queue panels, but be omitted from the folder/file names when the download is saved - ideally for both BBC and ITV programmes. The "sNNeMM" convention is sufficient for my needs.

Thanks! (and thanks for the great work on this tool - it's really useful).

**Comment by Lordsnooty05** [comment] 2021-03-23 21:55
Can you not just change the naming the way you want it. I’ve been doing that for years because I also use PLEX via Synology Nas. Not everyone names their tv programs the same way and I think asking for a special way of naming may cause more problems  than its worth.

**Comment by adbeckett** [comment] 2021-03-24 18:53
By "change the naming the way you want it" do you mean create a fork of get-iplayer-automator? Or do you mean manually change the file names afterwards? (which is a pain). Maybe I've misunderstood what you're saying?

I wonder whether some way of defining a template for naming would be useful, with placeholders for the various bits of information (something like "%P - %S.%I.%E" where %P is the program name, %S the season part, %I the sMMeNN part, %E the episode part). There could be a default, but might give flexibility to those who want it. That may be just too complicated though for most users. 

Either way, it's just a suggestion for improvement, particularly for those of us using Plex.

Andrew

**Comment by Lordsnooty05** [comment] 2021-03-25 00:49
I use a fantastic app on my mac called "A Better Finder Rename 11" and can be found at https://www.publicspace.net/ABetterFinderRename/index.html 
It is probably mainly used for renumbering Photos but I use it for TV Shows and Series and it is a breeze to use and yes I use a template ....something like this:-

01 Line of Duty Series 6  Episode 01 
02 Line of Duty Series 6  Episode 01 

(but I leave the episode numbers out) with a template like           Line of Duty Series 6 Episode
and it fills in all the numbers and does it very quickly...a couple of seconds and it is done and Plex recognises all my files...never had a problem

**Comment by skovatch** [comment] 2021-03-26 05:46
This turns out to be a regression. ITV always uses XBMC naming for shows, which is <series name>.s<season#>e<episode#>.<episode name>. I had changed series name for ITV shows to append the season so you can see it in the download queue, not realizing it affects the file name.

'Show name' is the display name for a program. It's a combination of series name and season number if it exists. Series and Episode name are defined things, and shouldn't ever be modified, or these kinds of problems happen.

**Comment by skovatch** [comment] 2021-03-31 16:21
Fixed in v1.21.7

**Closed by skovatch** 2021-03-31 16:21 UTC
