### ISSUE TITLE
BBC Programmes not downloading at maximum resolution

### ISSUE THREAD

**Issue by j3d1c4nna** [Ascoware/get-iplayer-automator#88] opened 2017-11-24 11:48 UTC
Hi

I'm running GIA 1.9.11 on my iMac (High Sierra 10.13.1).

In 'Download Formats', the only item I have for BBC is 'Best' and both the boxes are checked for 50FPS and better quality audio. I'm finding that the downloaded shows aren't in HD format though. I've noted below the log from an example I tried recently.

When I play the programme in VLC and check the statistics, I can see that the display resolution is 832 x 468. As a comparison, if I download the exact same programme using another app I have called Downie 3, its download displays at the full 1280 x 720. I don't want to use anything other than GIA, so am hoping that this issue can be addressed.

If you need any more information, please let me know.

=================
AppController: Starting Downloads
b09djvnf: Radio 2 In Concert - Deep Purple: Retrieving Metadata For PID

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

Downloading Show 1/1:
BBC Download (ID=b09djvnf): Downloading Radio 2 In Concert - Deep Purple
INFO: 0 matching programmes
WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Downloading tv: 'Radio 2 In Concert - Deep Purple (b09djvnf) [original]'
INFO: Downloaded: 799.84 MiB (01:11:12) @ 20.71 Mibit/s (hlsvhigh1) [audio+video]
INFO: Finished downloading to file: /Users/xxRemovedxx/Movies/TV Shows/Radio 2 In Concert/Radio 2 In Concert - Deep Purple ((hlsvhigh)).video.ts
INFO: Downloaded: 70.42 MiB (01:11:12) @ 6.40 Mibit/s (hvfxsd1) [audio]
INFO: Finished downloading to file: /Users/xxRemovedxx/Movies/TV Shows/Radio 2 In Concert/Radio 2 In Concert - Deep Purple ((hlsvhigh)).hqa.audio.ts
INFO: Converting to MP4
INFO: Tagging MP4
BBC Download (ID=b09djvnf): Radio 2 In Concert: Deep Purple Completed Successfully

AppController: Downloads Finished
Adding Radio 2 In Concert: Deep Purple to iTunes

Thanks

Doug

**Comment by skovatch** [comment] 2017-11-25 17:03
A few comments... I see you got hlsvhigh1 format, which is surprising since you said you have 'Best' selected. It's possible that that's the highest resolution available for streaming.

It could also be the case that not having DVF format is the problem. I find that the DASH format is often in 50 fps/HD quality, but it creates a video that isn't playable. I think I have a solution for that; you should see a fix in a day or two.

Regarding Downie.... For $13 you get a fully supported app that downloads and converts an HLS stream to MP4, and does so quickly! If it did the MP4 tagging so it would show up in iTunes properly I'd use that myself! 

I like free as in beer as much as anyone else, but if someone is charging a reasonable price for something you use on a daily basis, why wouldn't you buy it? Nothing personal, but that seems like a no-brainer.

**Comment by j3d1c4nna** [comment] 2017-11-25 18:32
Hi

Thanks for replying. I'm not sure I understand the DVF / DASH stuff, but I'll look out for a fix when it comes. 

I've only recently found Downie, which is very impressive, but the lack of file tagging is a nuisance for me. I use it mostly for YouTube, if I'm honest and hasn't even realised it could tackle iPlayer content until s couple of days ago. I'm not sure what point you were making about a no-brainer, but I've used GIA for many years now and have much affection for it and its sophisticated functionality. If the resolution issue is resolved, it'll still be my number one go to app for iPlayer content. Would happily pay for it too. 

Thanks

**Comment by raythw** [comment] 2017-11-26 10:43
No problems for me with HD: I seem to get it all the time for current programmes. 50FPS isn’t working, but that isn't the end of the world. As for Downie not supporting tags, well, you can add them pretty quickly using Subler or similar, and then open the file manually with iTunes, although nothing compares to GIA!

**Comment by j3d1c4nna** [comment] 2017-11-26 11:00
Nothing does compare to GIA, that's true! :-)
Will have a look at subler, thanks. 

Out of interest, have you tried to grab the programme detailed in my log file, to see if it's just me that's having the issue?
Cheers

**Comment by raythw** [comment] 2017-11-26 11:43
It's not you, j3! I get the same resolution. It's also the same if you use GetiPlayer via the Terminal, so the problem is perhaps deeper than GIA itself...

**Comment by raythw** [comment] 2017-11-26 16:04
PS: Downie is very good indeed. It also gets programmes at 50FPS...

**Comment by j3d1c4nna** [comment] 2017-11-26 16:09
Yeah, it's very good. Doesn't search iPlayer, or do the series link stuff, but a top notch downloader. 

I had a look at subler, but couldn't really get to grips with it, in regards to updating a file with metadata. I'll need to have another play with it.

**Comment by sleaux-meaux** [comment] 2017-11-26 16:10
get_iplayer itself can easily download the file you want:

    get_iplayer --pid b09djvnf --fps50 --version editorial

This looks like a case where an edited version ("editorial") of a programme was posted with additional media streams compared to the original version (labelled "original"). Given a choice, get_iplayer prefers the original version, which in this case lacks HD streams. To override that default behaviour you need to break out of GiA and use get_iplayer itself. Downie appears to just take the first version in the programme's iplayer playlist, which in this case is "editorial", the one you're after, so that may be a bit of a happy accident.

**Comment by skovatch** [comment] 2017-11-26 16:21
Regarding this:

> This looks like a case where an edited version ("editorial") of a programme was posted with additional media streams compared to the original version (labelled "original"). Given a choice, get_iplayer prefers the original version, which in this case lacks HD streams.

One change I am making is taking out the `--version default` when `audiodescribed` or `signed` isn't needed. This fixes a related bug, and it sounds like it will take care of this, too.

Using @sleaux-meaux 's example, you could remove the `-version editorial` and get_iplayer will fetch the highest resolution 'editorial' version. Thanks for noticing that, as I think it's the core of the problem here.

**Comment by sleaux-meaux** [comment] 2017-11-26 16:46
> One change I am making is taking out the --version default when audiodescribed or signed isn't needed. This fixes a related bug, and it sounds like it will take care of this, too.

It won't. The version labelled "original" would still be used if no --version argument is supplied.

**Comment by skovatch** [comment] 2017-11-26 16:58
Looks like it to me...

```
[skovatch:~/Movies/TV Shows] $ get_iplayer --pid b09djvnf --tvmode best --fps50 
get_iplayer 3.06-homebrew, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.


Matches:
INFO: 0 matching programmes
WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Downloading tv: 'Radio 2 In Concert - Deep Purple (b09djvnf) [editorial]'
INFO: Downloaded: 64.76 MiB (01:11:17) @ 0.64 Mibit/s (dvfhd1) [audio]          
 16% [====                     ] ETA: 02:07:12 (dvfhd1) [video]
```

**Comment by raythw** [comment] 2017-11-26 17:01
That's certainly HD, skovatch! Is it possible to get HQ sound on that type of stream at the same time?

**Comment by skovatch** [comment] 2017-11-26 17:03
That part is out of my control, I'm afraid. get_iplayer is fetching the audio and video separately and then recombining it with ffmpeg. I'll dig in to get_iplayer some more, as there might be some setting I'm not aware of, and it may be specific to dvf format streams.

**Comment by raythw** [comment] 2017-11-26 17:07
Many thanks, skovatch! It's great you're continuing working on all of this. Please don't 'do yourself in' though!

**Comment by raythw** [comment] 2017-11-26 17:10
j3d1c4nna: If you open a video file in Subler and click on the search magnifier at top right you can find metadata that matches the file concerned, including thumbnails. If the programme isn’t on the online databases you can edit the file manually. An invaluable tool, IMHO!

**Comment by j3d1c4nna** [comment] 2017-11-26 17:13
Thanks all. Apologies for opening up a can of worms!

**Comment by raythw** [comment] 2017-11-26 17:14
BTW, Downie doesn’t download HQ sound from iPlayer...

**Comment by skovatch** [comment] 2017-11-26 17:20
@j3d1c4nna No worries, this ended up being a very helpful find! I end up learning a lot about the world of streaming video through this project.

**Comment by skovatch** [comment] 2017-11-26 17:20
Closing, this should now be fixed in v1.9.13.

**Closed by skovatch** 2017-11-26 17:20 UTC

**Comment by sleaux-meaux** [comment] 2017-11-26 17:23
> Looks like it to me...

That's not what I see, so we'll have to agree to differ:
```
$ get_iplayer --pid b09djvnf --tvmode best --fps50
get_iplayer 3.06_1-homebrew, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.

Matches:
INFO: 0 matching programmes
WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Downloading tv: 'Radio 2 In Concert - Deep Purple (b09djvnf) [original]'
  2% [                         ] ETA: 00:03:15 (hvfxsd1) [audio+video]
```
It is odd that DASH ("dvfhd") shows as your stream format. That's not normal for get_iplayer (HLS is preferred), and not very desirable.

**Comment by skovatch** [comment] 2017-11-26 17:24
Whoa.... fascinating. Are you using the homebrew install or did you install it manually?

**Comment by raythw** [comment] 2017-11-26 17:34
skovatch: I don't know about him but I used the Homebrew install. As for audio, no it was at 96kbps. Worse still, I've tried get_iplayer --pid b09djvnf --tvmode best --fps50 AGAIN and now I've got hvfxsd1 video with sound at 48 kbps. There seems to be something random here. Perhaps --version editorial IS needed...

**Comment by raythw** [comment] 2017-11-26 17:38
OK, ran it again with --version editorial and I got hvfhd1 (at 50FPS), but with sound at 48kbps. Hope that helps...

**Comment by sleaux-meaux** [comment] 2017-11-26 17:39
> Whoa.... fascinating. Are you using the homebrew install or did you install it manually?

Homebrew. But I see now you're not in the UK, which might make a difference. This is what I see in the output from `get_iplayer --pid b09djvnf --info`:

```
modes:          editorial: dvfhd1,dvfhd2,dvfsd1,dvfsd2,dvfxsd1,dvfxsd2,dvfhigh1,dvfhigh2,dvfxhigh1,dvfxhigh2,dvflow1,dvflow2,hlshd1,hlsvhigh1,hvfhd1,hvfhd2,hvfhd3,hvfsd1,hvfsd2,hvfsd3,hvfxsd1,hvfxsd2,hvfxsd3,hvfhigh1,hvfhigh2,hvfhigh3,hvfxhigh1,hvfxhigh2,hvfxhigh3,hvfstd1,hvfstd2,hvfstd3,hvflow1,hvflow2,hvflow3
modes:          original: dvfxsd1,dvfxsd2,dvflow1,dvflow2,hlsvhigh1,hvfxsd1,hvfxsd2,hvfxsd3,hvfhigh1,hvfhigh2,hvfhigh3,hvfxhigh1,hvfxhigh2,hvfxhigh3,hvfstd1,hvfstd2,hvfstd3,hvflow1,hvflow2,hvflow3
```
It seems like you're not seeing either the "original" version or any of the HLS streams.

**Comment by raythw** [comment] 2017-11-26 17:42
I'm also in the UK and I get the same...

**Comment by sleaux-meaux** [comment] 2017-11-26 17:42
@raythw : Are you sure you're reading the audio bit rate and not the the sample rate (48 kHz for these files)?

**Comment by skovatch** [comment] 2017-11-26 17:46
Yep, I'm not seeing "original":
```
modes:          editorial: dvfhd1,dvfhd2,dvfsd1,dvfsd2,dvfhigh1,dvfhigh2,dvfxhigh1,dvfxhigh2
```

**Comment by raythw** [comment] 2017-11-26 17:51
Oops, Media Inspector's gone gah-gah and not showing bitrate, only sample rate, plus brain failed. Apologies!
