### ISSUE TITLE
Proxy Support broken for ITV ( not tried BBC ) in 1.11.1

### ISSUE THREAD

**Issue by GameCrazi** [Ascoware/get-iplayer-automator#134] opened 2018-03-20 21:12 UTC
Trying to download via proxy reports that ITV thinks you are outside of the uk . 
Tailing my proxy server log file I see nothing coming from GiA .

**Comment by sleaux-meaux** [comment] 2018-03-20 23:56
It looks like the proxy isn't being set in the runtime environment for ffmpeg when it is invoked to download an ITV HLS stream. I think that would have to be fixed in code. As a workaround, you can try launching GiA from the command line like this:

    http_proxy=<proxy_url> '/Applications/Get iPlayer Automator.app/Contents/MacOS/Get iPlayer Automator'

assuming it is installed in /Applications.

**Comment by GameCrazi** [comment] 2018-03-21 01:04
In ITVDownload.swif. I changed

`           configuration.connectionProxyDictionary = proxyDict;
`

to

`configuration.connectionProxyDictionary = [
                kCFNetworkProxiesHTTPEnable: true,
                kCFNetworkProxiesHTTPProxy: proxy.host,
                kCFNetworkProxiesHTTPPort: proxy.port,
                kCFNetworkProxiesHTTPSEnable: true,
                kCFNetworkProxiesHTTPSProxy: proxy.host,
                kCFNetworkProxiesHTTPSPort: proxy.port,
            ]`

which then  works  with the http_proxy=<proxy url> workaround . 

So there are 2 issue I feel .

**Comment by GameCrazi** [comment] 2018-03-21 01:05
also note that we no longer have the progress bar -

**Comment by skovatch** [comment] 2018-03-21 04:34
Should be fixed in 1.11.2, but I don't use a proxy server so I can't test it.

**Comment by skovatch** [comment] 2018-03-21 04:35
Progress bar sometimes doesn't appear because ffmpeg doesn't print out a header, or it does but it's not being captured.

**Closed by skovatch** 2018-03-21 04:34 UTC

**Comment by sleaux-meaux** [comment] 2018-03-21 12:45
ffmpeg needs a full URL for proxy

**Comment by Vangelis66** [comment] 2018-03-22 03:29
@skovatch , @sleaux-meaux 

I have just posted a lengthy but very informative [comment](https://github.com/rg3/youtube-dl/issues/15925#issuecomment-375161089) in youtube-dl' tracker, explaining in detail the newly implemented,  much stricter, geo-location blocking scheme on ITV Hub; whereas a mere week ago one could access from overseas the HLS playlist data with a simple hack and then fetch the fragments DIRECT, neither of the above is now possible; both playlist (master and variants) and fragments are now geo-fenced!

As for what concerns GiA, I gather you have delegated HLS stream decryption/downloading to FFmpeg; the cause of this reported issue is this new "hard" geo-block imposed by ITV; in the recent past, GiA's proxy would only be used to access stream data, while the stream itself would be downloaded DIRECT; now, with the stream itself being geo-fenced, the stream downloader (in this case FFmpeg) must also use GiA's proxy...

@skovatch 
I hope you don't mind me posting this, you said you don't use proxies yourself, I hope you now have a much clearer picture of what's been going on under the hood (make that "under the bonnet" for the UK users!) ...
