### ISSUE TITLE
ITV - None of the specified formats were available 

### ISSUE THREAD

**Issue by mrchrisoliver** [Ascoware/get-iplayer-automator#87] opened 2017-11-22 20:24 UTC
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Downloading Coronation Street - Wed Nov 22 - 7:30pm (Doesn't happen on all episodes, just random ones)
I have all format options starting from HD listed in ITV TV Show Formats

*What is the expected output? What do you see instead?*
I get the error: None of the specified formats were available. Please go to Preferences -> Other Formats and add at least one download format to the list.

*What version of GiA are you using? On what version of OS X?*
GiA Version: 1.9.11 - MacOS 10.13.1

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

Coronation Street - Wed Nov 22 (7:30pm)

*Please provide any additional information below.*

**Comment by markdmathias** [comment] 2017-11-22 21:38
I am having the same issue, with the same episode, also had one last Friday with the same issue and it worked later on. Could it be something funny that ITV is doing?

**Comment by skovatch** [comment] 2017-11-23 00:20
When I search for Coronation Street I get two entries for Wednesday, 22 November. When I tried to download both of them, one reports "None of the specified formats are available", but the other one works as expected. I'm not sure what's going on in the listings that would cause two entries to show up, nor if it's possible to detect the invalid/odd entries.

**Comment by mrchrisoliver** [comment] 2017-11-23 01:00
There should be double entries for Monday, Wednesday, and Friday(2 Episodes shown 7:30 and 8:30), the first episode for Wed Nov 22 still doesn't work, but the second (8:30pm) episode worked perfectly.

**Comment by blloyd78** [comment] 2017-11-26 10:30
Similar issue with The Protectors on Sunday 26th November. Neither the iPlayer Automator integrated search, or the Use Current Webpage function work.

**Comment by whitedb** [comment] 2017-11-26 17:37
I have the same problem. Just tried to get an issue of the protectors from Nov 26th and GIA crashes.  I tried use current web-page and via the application. I note that the preview picture on the iTV player website for this episode does not show a picture but it does play in the webpage.

Note that Thunderbirds from Sat Nov 25th will download.

**Comment by approtech** [comment] 2017-11-27 22:20
I can confirm that "The Protectors" Series 1 Episode 10 (shown Nov 26th) won't download in GiA 1.9.13 - even with all six possible ITV formats selected in preferences.
The log file simply says:

--------------------------------

Downloading Show 2/18:

ITV Download (ID=ENT1315/0022): Downloading The Protectors - Series 1 - Episode 10 - ENT1315/0022
INFO: Preparing Request for Auth Info
DEBUG: Metadata URL: http://mercury.itv.com/PlaylistService.svc
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
DEBUG: Metadata response: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><GetPlaylistResponse xmlns="http://tempuri.org/"><GetPlaylistResult><Fault xmlns=""><faultcode>InvalidEntity</faultcode><faultstring>Video has no renditions for platform DotCom</faultstring></Fault></GetPlaylistResult></GetPlaylistResponse></s:Body></s:Envelope>
DEBUG: Metadata processed: seriesName=(null) dateString=(null) episodeName=(No Episode Name) episodeNumber=10 self.thumbnailURL=(null) subtitleURL=(null) authURL=(null)
DEBUG: Retrieving Playpath
DEBUG: Parsing MediaFile entries
DEBUG: Searching for itvRate match
DEBUG: Searching for bitrate match
ITV Download (ID=ENT1315/0022): ERROR: None of the modes in your download format list are available for this show. Try adding more modes if possible.

----------------------------------

Previous episodes 1-9 have downloaded fine; other shows on ITV continue to be fine.
This episode of The Protectors plays fine in the ITV Hub in a browser.

**Comment by erikmh** [comment] 2018-01-01 13:56
I can confirm this with

- The Protectors, Series 1, episodes 13, 15, and 16
- Victoria, Series 2, episode 9
- Grantchester, Series 1, episode 2
- Bugsy Malone (film)

In addition, asking Maigret Season 2 episode 2 to download yields something called "Utterly Outrageous Celebrity Frock Ups." At this point, I'm finding far more ITV shows do **not** download than do.

**Comment by edjonesy** [comment] 2018-02-27 15:44
It seems to be happening more and more, I'm in the UK and NOT using a proxy.

It's happening with Season 2 Episode 2 of Marcella and Lethal Weapon Season 2 Episode 7.

BBC seems to be working fine and ITV finds the correct TV shows, just won't download any as "None of the specified formats were available".

Using Mac OS 10.12.6.

**Comment by hugofalkman** [comment] 2018-02-27 16:04
Lethal Weapon S2E7 is special, the program just isn’t there, also Downie can’t find it.

Marcella S2E2 no problem for Downie.

HF

**Comment by jchhenderson** [comment] 2018-02-27 16:09
None of Lethal Weapon will play on ITV right now - this is an issue with ITV and not get-player-automator.

**Comment by hugofalkman** [comment] 2018-02-27 16:29
Lethal Weapon S2E1-6 do not stream from the ITV hub, but GiA downloaded them ok anyway.

HF

**Comment by edjonesy** [comment] 2018-02-27 17:06
GiA keeps trying to download Lethal Weapon s02s07 as the show is set up in PVR auto record mode, so somehow it's finding it, but not downloading it unlike the first 6 episodes, odd.

As for Marcella s02e02, just tried it on my machine at work, that won't download it either, finds the show but won't download, that Mac is running 10.13.3.

@hugofalkman what is Downie? Another app?

**Comment by ian02054** [comment] 2018-02-27 17:13
I too have trouble with marcella s2e2 and james martins american adventure
e8,9,11. Same error on 2 macs with all itv formats enabled. Also still not
maintaining the pvr queue both before and after this mornings update 1.10

**Comment by hugofalkman** [comment] 2018-02-27 17:15
@edjonesy see issue #95.

@skovatch  please close this issue as duplicate of #95

**Comment by skovatch** [comment] 2018-02-28 03:54
I agree, we only need one bug tracking this.

**Closed by skovatch** 2018-02-28 03:54 UTC
