### ISSUE TITLE
Invalid Page Error when attempting to download Radio program with "Use Current Webpage"

### ISSUE THREAD

**Issue by whitedb** [Ascoware/get-iplayer-automator#110] opened 2018-02-24 12:35 UTC
Started getting this error Feb 24th.  I received the message:
 **Invalid Page: https://www.bbc.co.uk/programmes/b09qgxd7**
when trying to download some music from the iPlayer Radio pages.  If I use search within Get iPlayer Automator application and "Add to Queue" for the concert I want then there is no problem (it gets the same PID as is in the rejected webpage).  My browser was on the correct page, the tab was foremost and the music would play in my browser.  I have Get higher-quality audio enabled and this is the version that is downloaded.  I changed the audio setting and it did not make any difference. 
I restarted both GIA and Safari but the problem persists.

Not sure what is going on.  There was no GIA log generated.

The problem is occurring on both my Macs, one running Sierra and the other one El Capitan.

**Comment by Radar68** [comment] 2018-02-24 13:08
Same here.
Clumsy workaround to this is....

i)  Add ANY BBC iPlayer TV show to queue.  Anything will do so long as it goes into the queue.
ii)  Get the PID of the Radio show you want to download
iii)  Click on the PID of the TV show in the queue and paste the Radio show PID in its place
iv)  Start the download.  The PID will be checked, the Show Name will update to the Radio show and the download will work.

Unfortunately you can only do one show at a time and you'll need to repeat the entire process for each Radio show download you want.  No ideal but hope this helps until the issue is fixed.

**Comment by sleaux-meaux** [comment] 2018-02-24 13:57
Simpler workaround: https://github.com/Ascoware/get-iplayer-automator/issues/108#issuecomment-368062145

**Comment by ElsonRoa** [comment] 2018-02-24 13:58
That tip works fine Radar68, so thanks for that. Also I've found that you can click the + icon at bottom left of the GIA window. That generates a blank line. You can then double click on the blank PID box and past in the PID taken from the relevant browser window. GIA then adds the correct broadcast name when downloading begins.

**Comment by whitedb** [comment] 2018-02-24 14:43
Thanks for the great suggestions.

**Comment by skovatch** [comment] 2018-02-25 16:16
Reopening, since I found the spot where GiA isn't handling https-based pages correctly.

**Comment by skovatch** [comment] 2018-02-25 16:44
Now fixed in v1.9.15

**Closed by skovatch** 2018-02-25 16:44 UTC

**Comment by ElsonRoa** [comment] 2018-02-26 02:38
Thank you for the prompt update to GIA. Much appreciated.


--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com

25. Feb 2018 17:44 by notifications@github.com:
