### ISSUE TITLE
After working fine, today GiA crashes when opening:-

### ISSUE THREAD

**Issue by OBEngineer** [Ascoware/get-iplayer-automator#118] opened 2018-03-12 11:47 UTC
**This issue tracker is not a discussion forum, so don't use it as such.  If you wish to discuss the BBC, iPlayer or anything else that is not related to an actual problem with the current release of GiA, post in an appropriate forum, not in this issue tracker.**

**STOP! DO NOT submit a ticket if you are reporting that you are unable to download a program from outside the UK**.

If you need an explanation, read [this](https://github.com/Ascoware/get-iplayer-automator/wiki/No-Support-for-GiA-Outside-the-UK). If you ignore this instruction, your ticket will be closed with no further action. You can fib about your location if you like, but you will only be wasting your time. If you are using GiA within the UK, continue with the instructions below.

Before creating a new ticket, search the current open and closed tickets to see if your issue has already been reported. Use the search box at the top of the page to do so. You can also use the links below to view open and closed tickets in list form.

#### [Closed tickets](https://github.com/Ascoware/get-iplayer-automator/issues?q=is%3Aissue+is%3Aclosed)

If you create a ticket for an issue that has already been reported, your ticket will be closed with no further action. If you are certain your issue has not yet been reported, continue with the instructions below.

Create a succinct title describing your issue in the `Title` field above, then provide the information requested below. If you do not provide the requested information, your ticket will be closed with no further action.

If you cannot download a program, provide a verbose log of the attempt. See [Verbose Log](https://github.com/Ascoware/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE program. DO NOT post a massive log covering multiple multiple program downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/Ascoware/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

**Delete the instructions above before submitting your ticket.**

---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*

**Comment by OBEngineer** [comment] 2018-03-12 11:50
Using OSX 10.13.3    iMac 18.3   

GiA Crases immediately upon opening. Worked perfectly until then. Thanks to all concerned.

Tried re-start, tried re-load. Noluck. Any ideas?


Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString appendString:]: nil argument'
terminating with uncaught exception of type NSException
abort() called

**Comment by MistressMB** [comment] 2018-03-12 11:53
Same problem here.

**Comment by jchhenderson** [comment] 2018-03-12 11:57
woah - just ran it to check this and had the same problem.

Worked fine only a few hours ago.  I just checked with my sister who is currently on a business trip in Boston.  It's still working for her and Boston is 4hrs behind us.

I am on a MacBook Pro, she is on a Mac Air - we both have v1.10.0

**Comment by OBEngineer** [comment] 2018-03-12 12:24
**Working correctly now.**
I have done nothing. Very odd. I'm sorry I started the issue!

I have done a full test and all worked correctly.

I wonder what will happen when I restart the machine next time !??



_**Sincere **thanks** to the team behind GiA.**_

**Comment by jchhenderson** [comment] 2018-03-12 12:25
yes - working here now as well!

**Comment by OBEngineer** [comment] 2018-03-12 12:26
I did full re-start. Nothing.
Then after a period of a few minutes... great..

Very very odd.

**Comment by jchhenderson** [comment] 2018-03-12 12:27
...I didn't do anything - simply checked both times when you posted.

**Comment by MistressMB** [comment] 2018-03-12 13:17
How incredibly odd! Mine's all working fine again now as well!! Thanks so much to everyone involved in writing and maintaining this ap, I sincerely love it!

**Comment by OBEngineer** [comment] 2018-03-13 12:12
Done it again. After official 'Apple' shutdown. ie it wasn't a crash or anything. I went out of the house and shut the imac down. Upon restart, GiA failed for the same reason:-

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString appendString:]: nil argument'
terminating with uncaught exception of type NSException
abort() called


I shall see what transpires.... wish me luck.

**Comment by jchhenderson** [comment] 2018-03-13 13:11
Yeo - just checked and it crashed with me for the same error message (worked perfectly earlier today).

...this is quite strange and expect it too be working again later as per yesterday.

Note:  I haven't logged off/on/restarted since this began.

**Comment by mutantcamel** [comment] 2018-03-13 14:32
This seems to be an issue with updating the ITV feeds on my machine.

**Comment by skovatch** [comment] 2018-03-13 14:42
I'm on it. There's something weird with ITV pages today, but I have a quick fix.

**Comment by skovatch** [comment] 2018-03-13 14:50
Fixed in v1.10.1, but you may have to download it manually since the crash happens before the updater has a chance to run.

**Closed by skovatch** 2018-03-13 14:50 UTC

**Comment by OBEngineer** [comment] 2018-03-13 15:00
skovatch, sincere thanks for everything you do. 

My GiA crashes before it has chance to do anything. 

I don’t think that the ITV aspect is anything to do with the problem some are having. 

On my iMac, - I am about to fire up a 2012 non retina MBP. - GiA crashes in less than one second. It can’t have touched ITV at that point. 

Hope these observations help. 

Regards.

**Comment by skovatch** [comment] 2018-03-13 15:05
I reproduced it -- it's crashing as it processes old entries from the cache, which is one of the first things the app does. That's why it's crashing before it even gets to the part where it fetches new ITV listings or the update feed.

Get the new version https://github.com/Ascoware/get-iplayer-automator/releases/tag/v1.10.1 and you should be in better shape.

**Comment by Emgeelondon** [comment] 2018-03-13 15:05
I found a way round the 'crash before the updater' if you want to avoid updating manually.....
1-Turn off wifi/connection
2- Load GIA, wait for ITV load to 'timeout'
3- Edit preferences to deselect ITV
4- Turn wifi on/reconnect
5- 'Check for updates' option from topline menu
6- Reselect ITV in preferences
7- Back to normal  :-)

Hope it helps.....

**Comment by OBEngineer** [comment] 2018-03-13 15:56
v1.10.1 perfect.

skovatch, brilliant. 

Much appreciated.

**Comment by Emgeelondon** [comment] 2018-03-13 16:07
Ditto!
:-)
