### ISSUE TITLE
"Use current webpage" not working

### ISSUE THREAD

**Issue by petrfaitl** [Ascoware/get-iplayer-automator#201] opened 2018-09-02 05:25 UTC
After update version 1.13.14 (20180831001) I'm unable to use "Use current webpage" feature. Modal window reports `Programme Page Not Found. Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page.` 

I have tried going to another episode or changing a browser to no avail.

*What version of GiA are you using? On what version of OS X?*

High Sierra 10.13.6
Chrome Version 69.0.3472.3 (Official Build) dev (64-bit)
Chrome Version 70.0.3534.4 (Official Build) dev (64-bit)

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

https://www.bbc.co.uk/iplayer/episode/p05dt3hg/upstart-crow-series-2-6-sweet-sorrow

**Comment by skovatch** [comment] 2018-09-03 19:04
I see the problem... For BBC shows, GiA needs to look at the page source, but on Chrome you need to run JavaScript to get it. Chrome changed recently and you have to explicitly allow running JavaScript in an AppleEvent.

For now, you can work around this by using Safari (!) or turning on "Allow JavaScript From AppleEvents" from the View -> Developer menu item.

I think I can fix it so this isn't required, but it won't be able to distinguish a series page from an episode page.

**Comment by petrfaitl** [comment] 2018-09-03 21:30
Thanks for the response. The "Allow JavaScript From AppleEvents" workaround works on Chrome. Safari, on the other hand is having similar problem and the workaround is not working (Allow JavaScript From AppleEvents doesn't stick). Anyway better stick with Chrome ;)

**Comment by skovatch** [comment] 2018-09-03 22:00
Hmm.. that's surprising because Safari doesn't need JavaScript to read the page contents. Ah well, I will push out an update soon, so it doesn't matter.

**Comment by deinfluence** [comment] 2018-09-09 23:59
I am getting a similar issue using the "Use Current Page" option in Google or Safari with 1.13.14 or 1.13.15 and only occurs with ITV and not BBC. The issue is not present in 1.13.13. I am not sure if this is the same issue or not.

Here is an example of the program I am trying to download:
The Only Way is Essex - Series 23 - Episode 1 or 2

![image](https://user-images.githubusercontent.com/27931868/45270319-4a3f5e00-b46a-11e8-97e5-4998768c0843.png)

**Comment by skovatch** [comment] 2018-09-10 01:37
@deinfluence Are you caching ITV shows? After getting the program ID from the webpage GiA will search to get the show metadata. It shouldn't fail with an error like that, but given that you said it works in 1.13.13, that's my guess.

**Comment by deinfluence** [comment] 2018-09-10 02:02
Hi @skovatch, no I am not caching any shows which is strange.
![image](https://user-images.githubusercontent.com/27931868/45272560-ff2e4680-b47b-11e8-9e20-280141e8f340.png)

**Comment by skovatch** [comment] 2018-09-10 04:14
Okay -- can you turn on ITV TV caching and try it again? That gives me a hint as to what's going on.

**Comment by deinfluence** [comment] 2018-09-11 00:45
@skovatch Yes - it works with ITV caching on with 1.13.15

**Comment by jchhenderson** [comment] 2018-12-19 12:10
I now have this problem in Safari and Firefox with both BBC and ITV and v1.13.18, whether I cache or not.

i.e. it doesn't work under any circumstances with any browser I have.


....but, I have another Mac also running 1.13.18 and it works fine.  Perhaps I can help diagnose this as I have a working and non working Mac?  ...the only difference I can see is that my working Mac (a Mac mini is still on MacOS 10.13.6)

**Comment by skovatch** [comment] 2019-01-04 19:30
What is the error you are seeing when try it?

**Comment by jchhenderson** [comment] 2019-01-07 00:45
Hi,

I get:

> Program Page not found
> Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page.

I have uninstalled/reinstalled and still get the same message.  My other Mac works fine.

thanks,
James.

**Comment by skovatch** [comment] 2019-01-07 07:01
On the machine that isn't working, is it running 10.14 (Mojave)? If so, go to System Preferences -> Security & Privacy -> Privacy tab -> Automation. 

Is Get iPlayer Automator in that list? Is it allowed to control Safari or Firefox?

**Comment by skovatch** [comment] 2019-01-07 16:01
Automation is a new category of things that the user must opt in to in Mojave. My hunch is that if the OS has asked for permission but it was denied, Get Current Webpage will fail. However it doesn't look any different from the error you get if the frontmost page is not a BBC page, so I'm trying to eliminate that possibility.

**Comment by jchhenderson** [comment] 2019-01-07 18:32
Yes!  ...that was the problem - thanks, skovatch :-)

**Comment by skovatch** [comment] 2019-01-07 18:47
Great! I’m going to close this, since there are other open issues for the other things mentioned here. I will also look into providing a better message when that happens, since we do get a callback/error when the permissions aren’t right.

**Closed by skovatch** 2019-01-07 18:47 UTC
Labels: bug
