### ISSUE TITLE
ITV downloads and searches are broken

### ISSUE THREAD

**Issue by skovatch** [Ascoware/get-iplayer-automator#126] opened 2018-03-19 20:59 UTC
Searches aren't working right now because the cache has no program IDs or URLs.

ITV has changed the layout of their program pages, and as a result the ITV listings scanning is now broken. It's not possible to use the 'Use current webpage' either, as the parsing code can't find the program data.

I am actively working on this, and also the ability to download non-RTMPDump-able programs.

Status:
[/] Scanning ITV Hub for available shows
[/] Downloading shows, either selected by "Get Current Webpage" or searching the cache
[/] Thumbnails for the program
[/] Handling inside/outside UK failures, and programs that don't have a streamable version
[ ] Subtitles

[/] means working locally
[ ] means work in progress

Once all of these are sorted I will release an update.

**Comment by skovatch** [comment] 2018-03-19 21:03
Things that aren't going to work (and may not have been working before):

- Resumable ITV downloads
- Certain platform-specific shows. I tried pretending to be Windows NT, but no luck. Generally speaking, if youtube-dl can't get it GiA won't be able to either.

**Comment by hugofalkman** [comment] 2018-03-19 21:15
Thanks @skovatch for opening this issue. Think it might be helpful if you close all other open issues referencing these problems, as duplicate of this new issue.

For all reading this -- note that what Scott is now with higher priority working on, means that issue #95 has lower priority and will resurface as soon as Scott fixes these immediate problems. Please don't open new issues for the problem in #issue 95 and consider the bypass of that problem by installing the Downie program.

**Comment by skovatch** [comment] 2018-03-19 21:18
This will also fix #95 as well. This new version will download any ITV content that Downie or youtube-dl can download.

**Comment by hugofalkman** [comment] 2018-03-19 21:21
Great 😀

**Comment by skovatch** [comment] 2018-03-19 23:17
All set in v1.11.0. A few notes:
- ITV is now using WebVTT for subtitles. I'll look for a WebVTT to Subrip converter if needed.
- THIS VERSION NOW REQUIRES MACOS 10.9 OR LATER! I'm using Swift for large parts of the app, and that has a minimum OS version of 10.9. I will update the README.

**Closed** 2018-03-19 23:19 UTC
Labels: bug

**Comment by hugofalkman** [comment] 2018-03-19 23:41
@scovatch i have no idea what a new format for subtitles means. What I know is since years I have been merging srt files into the mp4 files using subler for both BBC and ITV. So if no longer srt files for ITV, just tell me how to get the subtitles into the mp4 file.

**Comment by sleaux-meaux** [comment] 2018-03-19 23:52
@hugofalkman - Subler can merge WebVTT files.
