### ISSUE TITLE
Unable to download ITV content on Apple Silicon M1

### ISSUE THREAD

**Issue by ThisLifeIrl** [Ascoware/get-iplayer-automator#305] opened 2021-01-15 18:36 UTC
Since starting to use a M1 Mac a few days ago I seem to be unable to download any ITV content on it via GiA. I've read #296 
which suggests that GiA works on M1 and for BBC programs it works perfectly for me, just not ITV. 

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
- Open GiA, cache automatically updates 
- Add ITV program either from Safari via "Use Current Webpage" button or search for it within GiA and hit "Add to Queue" (trying both methods still result in the same outcome)
- Click start and the status changes briefly to Downloading before it changes to Download Failed
- Failed Download Popup appears saying : Problem unknown. Please submit a bug report...

I've tried downloading the same program on an Intel Mac running same version of GiA and MacOS and this works without any problems. I've also tried downloading other ITV programs and all result in the same error. 

*What version of GiA are you using? On what version of OS X?*
GiA v1.20.01, macOS Big Sur 11.1

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No and I'm located in the UK.

*What program are you attempting to download (full title, series and episode)? * 
The Pembrokeshire Murders: Series 1 - Episode 3
https://www.itv.com/hub/the-pembrokeshire-murders/2a6732a0003

*Please provide any additional information below.*
I'm able to download the program using youtube-dl via Terminal without issue. Couple of other things in case they're relevant:
- I've used Migration Assistant to copy over my files and settings from Intel Mac to Silicon
- Before the download fails it does create a folder labelled with the program title but the folder is empty.

*Verbose Log*
[Get iPlayer Automator M1 Download Failed Log.docx](https://github.com/Ascoware/get-iplayer-automator/files/5822340/Get.iPlayer.Automator.M1.Download.Failed.Log.docx)

**Comment by ian02054** [comment] 2021-01-15 18:56
I have had this sometimes happen… (and for this show as well it did) sometimes the Cache on the itv side doesn’t seem to work first time, but when I did the download again, it worked fine… sometime it is just a case of hitting “run” again, and it will work 2nd (or 3rd) time… sometimes I update cache again manually, and re-add the program..

**Comment by ThisLifeIrl** [comment] 2021-01-15 18:57
Yes, I had that on Intel Mac but after two or three attempts it would work. Sometimes it would fail halfway through the download too but again restarting it once, maybe twice and it would eventually succeed as you said. This time though I've tried around 15-20 times and every time is the same result.

**Comment by mteller2** [comment] 2021-01-18 20:23
Looking at the non-verbose log entries, this appears to be a youtube-dl issue as it terminates almost instantly.

**Comment by skovatch** [comment] 2021-02-26 04:33
Looks like the problem is an ffmpeg that crashes on an M1 Mac. get_iplayer shipped a new ffmpeg with 3.27, with a claim that they now work on M1. I'll try this on my wife's MacBook Air and try to confirm it.

**Comment by mteller2** [comment] 2021-02-26 07:38
I look forward to the results. If you need another Beta tester, I am willing — let me know and drop me a zip-file.

Thanks…..

Marc Teller ￼￼￼￼
mteller@mjtc.com (MBa)

**Comment by ThisLifeIrl** [comment] 2021-02-28 07:52
Hi, just tried version 1.21 and the issue persists, for me at least.

**Comment by mteller2** [comment] 2021-02-28 18:38
Oh Well! I tried using 1.20 on my Intel Mac Mini and it works so I do have a workaround. Given the number of embedded libs/tools in GiA, this could be any of them causing the issue. This is a natural downside of the layers within apps. I am sure that you will get to the bottom of it. Fortunately there is time as the roll-out is going slow in the transition to M1 processors.

Thanks for the update and if I can help, please let me know….

Marc Teller ￼￼￼￼
mteller@mjtc.com (MBa)

**Comment by skovatch** [comment] 2021-02-28 20:50
Looks like the problem is a combination of youtube-dl and ffmpeg. Youtube-dl decides that its hlsnatve extractor can't handle the stream it has found, so it wants to delegate the download to ffmpeg. But, the ffmpeg pulled in via get_iplayer was built with ffplay disabled, so it can't do the downloading, probably because get_iplayer never delegates downloads.

So that part is fixed by replacing ffmpeg with a different binary. Doing that gets ITV working again on Apple Silicon. I'd like to figure out why youtube-dl decides it cannot handle the decryption itself, though, as it happens on the command line as well.

**Comment by mteller2** [comment] 2021-03-01 00:53
I wonder if it is another Intel/M1 lower library issue that results in a failed check? Any way, this is progress…..

Thanks.

Marc Teller ￼￼￼￼
mteller@mjtc.com (MBa)

**Comment by ThisLifeIrl** [comment] 2021-03-02 12:56
Just tried another ITV download on v1.21.2 and it's now working correctly

**Comment by skovatch** [comment] 2021-03-23 16:47
OK, good to hear!

**Closed by skovatch** 2021-03-23 16:47 UTC
