### ISSUE TITLE
Invalid PID from Glasto coverage

### ISSUE THREAD

**Issue by turkeyphant** [Ascoware/get-iplayer-automator#48] opened 2017-06-26 20:20 UTC
e.g. can't download: http://www.bbc.co.uk/iplayer/episode/p056bxjf/glastonbury-2017-radiohead

**Comment by Lordsnooty05** [comment] 2017-06-26 21:58
I don't know but it worked for me. I have downloaded all the glastonbury episodes Are you using Safari? and are you downloading it via "Use Current Webpage" button?

**Comment by turkeyphant** [comment] 2017-06-26 22:31
Using Chrome. Same issue on Safari. Can you give a working PID as an example for the above URL because it adds to download queue correctly but then says invalid PID.

**Comment by Lordsnooty05** [comment] 2017-06-26 23:35
p056bxjf this is the PID. I tried to download it again and it worked.....no problem whatsoever but I am using Safari and also using "Use Current Webpage" button. The GiA that I am using is Version 1.9 (1841) with mac OS Sierra 10.12.5. on a iMac

**Comment by turkeyphant** [comment] 2017-06-26 23:36
Weird. I get the same PID. It says available but then says PID not found.

**Comment by Lordsnooty05** [comment] 2017-06-26 23:40
I don't know what is going on there because I am not getting that warning....are you using a vpn or something like that? I'm lost at how to help you but it works for me

**Comment by turkeyphant** [comment] 2017-06-26 23:43
No VPN or proxy.

`INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=p056bxjf): Downloading Unknown: PID Not Found
ERROR: Programe Type '' does not exist. Try using --refresh
BBC Download (ID=p056bxjf): Unknown: PID Not Found Failed

AppController: Downloads Finished`

**Comment by Lordsnooty05** [comment] 2017-06-26 23:48
Sorry can't help you. Where you able to download the other episodes of Glastonbury? or have they also failed?

**Comment by turkeyphant** [comment] 2017-06-26 23:49
Same issue on all.

**Comment by Lordsnooty05** [comment] 2017-06-26 23:53
Oh that is really weird. I have had NO trouble downloading all the episodes of Glastonbury. Have you tried uninstalling GIA completely and downloading a fresh copy and installing it again.

**Comment by turkeyphant** [comment] 2017-06-26 23:54
Yes I just reinstalled. And it works fine with get_iplayer for some reason.

**Comment by dolphino2** [comment] 2017-06-27 09:37
Also having the same issue as @turkeyphant 

Attempting to use GiA (1.9 - 1841) on OS X 10.12.5 and when searching for any glasto related content, via the "use current website" button, it retrieves the PID, but then when processing it, you receive status - available, however under show name you receive "unknown: PID not found".

It works fine for other non-glasto content.

**Comment by dolphino2** [comment] 2017-06-27 09:38
INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=p0557mwq): Downloading Unknown: PID Not Found
ERROR: Programe Type '' does not exist. Try using --refresh
BBC Download (ID=p0557mwq): Unknown: PID Not Found Failed

AppController: Downloads Finished

**Comment by turkeyphant** [comment] 2017-06-27 10:35
Using command line works fine and it seems it's "tv" programme type which Automator can't see:

```
INFO: Episode PID detected
INFO: Trying pid: p056bxjf using type: tv
INFO: Trying to download PID using type tv
INFO: pid not found in tv cache
Matches:
```

**Comment by skovatch** [comment] 2017-06-27 13:51
For those that are having a problem, can you turn on verbose mode and post your log? The errors are being generated by get_iplayer, but it's likely something isn't making its way into the command-line tool.

**Comment by turkeyphant** [comment] 2017-06-27 14:01
Amazingly I just loaded it up to turn on verbose it works now!

**Comment by dolphino2** [comment] 2017-06-27 14:17
I can confirm it is working aswell - started automatically without issue about 30 minutes after my post.  Tested with multiple glasto related items and all are now appearing to be fine to download.

**Comment by skovatch** [comment] 2017-06-27 14:53
Excellent -- I'll close this. If something else happens, let me know.

**Closed by skovatch** 2017-06-27 14:53 UTC
