### ISSUE TITLE
Marcella ITV Download problems

### ISSUE THREAD

**Issue by nickiplayer** [Ascoware/get-iplayer-automator#116] opened 2018-03-06 12:11 UTC
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Try to download series 2 episode 2 or 3

*What is the expected output? What do you see instead?*
None of the specified formats were available for download

*What version of GiA are you using? On what version of OS X?*
latest version on Sierra

*Are you using a web proxy? DNS proxy? VPN? VPS?*
no

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*
can however download all of series 1 and episode 1 of series 2 and other ITV programs as well for example this weeks Endeavour

**Comment by Vangelis66** [comment] 2018-03-06 15:29
Duplicate of https://github.com/Ascoware/get-iplayer-automator/issues/95, which itself is a dup of https://github.com/Ascoware/get-iplayer-automator/issues/87 (which was also probably duped in https://github.com/Ascoware/get-iplayer-automator/issues/98); however, the maintainer decided to close #87 and keep open #95, as that contains more input/info...

**TL:DR**

ITVHub currently do not always provide RTMPE streams (that GiA can harvest) for **all** their shows; there exist AppleHLS (AES 128 encrypted) streams for those programmes, that other solutions can cope with... See linked issues. In any case, the maintainer is already aware of this GiA predicament...

**Comment by jchhenderson** [comment] 2018-03-12 08:39
same problem here with Endeavour (was OK, now not with s05e06).  Downloaded OK with Downie.

**Comment by jchhenderson** [comment] 2018-03-12 09:09
@Lordsnooty05 - agreed.  I just posted the following in #115...

---
I emailed ITV (I am a UK resident) and they said that Lethal Weapon is only the following platforms:
**Virgin Media, iOS and Sky.**

He also wrote that it was available on their website via **Internet Explorer or Microsoft Edge**, but due to technical reasons it is not available via any other browsers.

Would emulating Internet Explorer help here?

J.

**Comment by hugofalkman** [comment] 2018-03-12 09:19
Please close this issue as duplicate of issue #95

**Comment by Lordsnooty05** [comment] 2018-03-13 17:14
I don't know if anyone from the UK is experiencing this but since the new update (today), I can't download anything from ITV!! Strange or what? t was working last night but today since the new update I tried to download the last episode from Marcella and it just wouldn't download. I tried to search for the Program and it said that there wasn't a program called Marcella....very strange. So anyone out there in the UK experiencing this same problem?

**Comment by sleaux-meaux** [comment] 2018-03-13 17:41
All the records in the ITV cache appear to be invalid (empty PID fields) and ignored in search results. I'm guessing that was the root cause for #118.

**Comment by skovatch** [comment] 2018-03-13 17:43
Searches aren't working right now because the cache has no program IDs or URLs. 

It looks like ITV have changed the layout of their program pages, and as a result the ITV scanning is now broken. It's not possible to use the 'Use current webpage' either, as the parsing code can't find the program data.

I'm at work now, so I have no ETA on when this will be fixed.

**Comment by Lordsnooty05** [comment] 2018-03-14 10:30
Scott, thanks a million for all your work keeping this app alive. When it is working it is the best around but it doesn’t help when channels like ITV mess about with their program layouts. Guys, give Scott time and space to work on a solution and stop moaning about the app not working, he knows and he working on it. Thanks

**Comment by sxmpete** [comment] 2018-03-16 14:15
Just used version 1.10.2 and still get "none of the modes in your download list are available" from ITV (attempting Endeavour S5E6)

**Comment by Lordsnooty05** [comment] 2018-03-16 14:28
Sxmpete please read:-

"Searches aren't working right now because the cache has no program IDs or URLs.

It looks like ITV have changed the layout of their program pages, and as a result the ITV scanning is now broken. It's not possible to use the 'Use current webpage' either, as the parsing code can't find the program data.

I'll investigate ASAP.".......Scott

Please give him time to work on it,  it appears the fault lies with the redesign of ITV Player

**Comment by hugofalkman** [comment] 2018-03-16 14:28
please close this issue as duplicate of issue #95.

You are causing Scott extra work by opening new issues for existing problems.

**Comment by skovatch** [comment] 2018-03-16 14:35
"Use Current Webpage" now works in 1.10.2, and will let you download a show again, but only if the show still has a streamable version available. That update only addressed the changes in metadata on show episode pages.

In related news, though, the new ITV episode pages make it much easier to find the URL I need to get the alternative method for downloading shows. That and some quick testing with ffmpeg shows me the way forward, so now I just need some time to implement it.

**Comment by skovatch** [comment] 2018-03-16 14:35
Duplicate of #95.

**Closed by skovatch** 2018-03-16 14:35 UTC
